name: Build VSCode extension

on:
  push:
    branches: '**'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout liberty-tools-vscode
        uses: actions/checkout@v3
        with:
          path: liberty-tools-vscode
      - name: Checkout lsp4jakarta
        uses: actions/checkout@v3
        with:
          repository: eclipse/lsp4jakarta
          path: lsp4jakarta
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Build Liberty Tools for VSCode
        working-directory: ./liberty-tools-vscode
        run: |
            npm install
            npm install -g vsce
            npm run build
            npm run buildJakarta
            npm run compile
            vsce package
      - name: Archive artifacts
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3        
        with:
          name: liberty-tools-vscode-${{ github.sha }}
          path: ./**/*.vsix
          if-no-files-found: warn
          retention-days: 7
